project:
  type: book

book:
  title: "量化投资课程讲义"  # 您的书名
  author: "汪小圈"      # 您的名字
  date: today
  chapters:
    - index.qmd          # 首页
    - 01_emh.qmd         # 第一节：有效市场假说
    - 02_capm.qmd        # 第二节：资本资产定价模型
    # - ...              # 更多章节，按照顺序添加 