project:
  type: book

book:
  title: "量化投资课程讲义"  # 您的书名
  author: "汪小圈"      # 您的名字
  date: today
  chapters:
    - index.qmd          # 首页
    - 01_emh.qmd         # 第一节：有效市场假说
    - 02_capm.qmd        # 第二节：资本资产定价模型
    - lab02_capmtest.qmd     # 第二节：CAPM实证检验
    - 03_ff3.qmd          # 第三节：三因子模型
    - lab03_ff3test.qmd    # 第三节：三因子模型实证检验
    - project1_factor.qmd  # 项目1：传统多因子投资
    - project2_ml_alt_data.qmd  # 项目2：机器学习与另类数据
